name : Ci Pipeline

on : push

jobs : 
  first_job : 
    runs-on : ubuntu-latest
    steps : 
      -name : checkout-code
        uses : actions/checkout@v4

      -name : python setup
        uses : actions/setup-python@v4
      
      -name : install requirements
        run : pip install tensorflow
      
      -name : run the file
        run : python src/basic.py
